export const SUMMARY_CARDS = [
  {
    id: 'total-assigned',
    title: 'Total Assigned',
    value: '16',
    note: 'All queued',
    tone: 'blue',
  },
  {
    id: 'high-priority',
    title: 'High Priority',
    value: '7',
    note: 'Urgent action needed',
    tone: 'red',
  },
  {
    id: 'sla-breaching',
    title: 'SLA Breaching',
    value: '3',
    note: 'Within 3 hours',
    tone: 'amber',
  },
];

/* The four stages an application moves through on the agent-1 panel. `stage` on
   a row is the 1-based step it currently sits on. */
export const APPLICATION_STEPS = [
  'Assigned',
  'Verification Started',
  'Decision Made',
  'Forwarded to A2',
];

/* Verification checklist, in the order it is shown. Each row carries its own
   `checklist` array of booleans-by-id; this is the label source. */
export const CHECKLIST_ITEMS = [
  { id: 'identity', label: 'Identity Verified' },
  { id: 'property', label: 'Property Verified' },
  { id: 'payment', label: 'Payment Verified' },
  { id: 'signature', label: 'Signature Verified' },
  { id: 'supporting', label: 'Supporting Docs Verified' },
  { id: 'complete', label: 'Application Complete' },
];

/* Headline counters on the pending-verification screen. */
export const PENDING_STATS = [
  { id: 'pending', tone: 'pending', label: 'Pending', value: '2', note: 'Not yet started' },
  { id: 'progress', tone: 'progress', label: 'In Progress', value: '1', note: 'Currently being verified' },
  { id: 'sla', tone: 'sla', label: 'Avg SLA Left', value: '4.2 hrs', note: 'Across all pending' },
];

/* Headline counters on the waiting-for-customer screen. */
export const WAITING_STATS = [
  { id: 'awaiting', tone: 'awaiting', label: 'Awaiting Response', value: '2', note: 'Query sent, no reply' },
  { id: 'reupload', tone: 'reupload', label: 'Re-upload Received', value: '1', note: 'Ready for re-verification' },
  { id: 'days', tone: 'days', label: 'Avg Waiting Days', value: '4.3', note: 'Days since query raised' },
];

/* Applications parked with the customer. A row carries `reupload` only once
   the customer has sent a replacement, which is what unlocks re-verification. */
export const WAITING_ROWS = [
  {
    id: 'APP-2024-00419',
    initials: 'PS',
    name: 'Priya Sharma',
    service: 'Building Plan',
    department: 'Urban Dev',
    priority: 'High',
    priorityTone: 'high',
    status: 'Waiting Customer',
    statusTone: 'waiting',
    appliedDate: '01 Jul 2024',
    waitingDays: 3,
    queriesRaised: 1,
    reupload: null,
  },
  {
    id: 'APP-2024-00421',
    initials: 'SP',
    name: 'Sunita Patel',
    service: 'Mutation',
    department: 'Registration',
    priority: 'Low',
    priorityTone: 'low',
    status: 'Query Raised',
    statusTone: 'query',
    appliedDate: '29 Jun 2024',
    waitingDays: 5,
    queriesRaised: 2,
    reupload: null,
  },
  {
    id: 'APP-2024-00428',
    initials: 'VS',
    name: 'Vikram Singh',
    service: 'Land Records',
    department: 'Revenue',
    priority: 'High',
    priorityTone: 'high',
    status: 'Waiting Customer',
    statusTone: 'waiting',
    appliedDate: '26 Jun 2024',
    waitingDays: 7,
    queriesRaised: 1,
    reupload: null,
  },
  {
    id: 'APP-2024-00422',
    initials: 'KR',
    name: 'Kiran Rao',
    service: 'Land Use Change',
    department: 'Urban Dev',
    priority: 'High',
    priorityTone: 'high',
    status: 'Re-upload Received',
    statusTone: 'reupload',
    appliedDate: '28 Jun 2024',
    waitingDays: 2,
    queriesRaised: 1,
    reupload: { previous: 'Site_Map_v1.pdf', current: 'Site_Map_v2.pdf' },
  },
];

/* Headline counters on the forwarded-to-agent-2 screen. */
export const FORWARDED_STATS = [
  { id: 'total', tone: 'total', label: 'Total Forwarded', value: '3', note: 'This month' },
  { id: 'approved', tone: 'approved', label: 'Approved by A2', value: '1', note: 'Final approval done' },
  { id: 'pending', tone: 'pending', label: 'Pending at A2', value: '2', note: 'Awaiting A2 decision' },
];

/* Applications handed to Agent 2. `status` is A2's verdict so far — still
   forwarded, or already approved by them. */
export const FORWARDED_ROWS = [
  {
    id: 'APP-2024-00425',
    initials: 'SI',
    name: 'Suresh Iyer',
    service: 'Building Plan',
    department: 'Urban Dev',
    priority: 'High',
    priorityTone: 'high',
    status: 'Forwarded',
    statusTone: 'forwarded',
    appliedDate: '25 Jun 2024',
    forwardedDate: '02 Jul 2024',
    agent: 'Agent 2 – Kavitha R.',
  },
  {
    id: 'APP-2024-00430',
    initials: 'MD',
    name: 'Mohan Das',
    service: 'Property Tax',
    department: 'Revenue',
    priority: 'Medium',
    priorityTone: 'medium',
    status: 'Approved',
    statusTone: 'approved',
    appliedDate: '22 Jun 2024',
    forwardedDate: '01 Jul 2024',
    agent: 'Agent 2 – Kavitha R.',
  },
  {
    id: 'APP-2024-00431',
    initials: 'LM',
    name: 'Lalitha Menon',
    service: 'Encumbrance',
    department: 'Registration',
    priority: 'Low',
    priorityTone: 'low',
    status: 'Forwarded',
    statusTone: 'forwarded',
    appliedDate: '20 Jun 2024',
    forwardedDate: '30 Jun 2024',
    agent: 'Agent 2 – Arjun K.',
  },
];

export const QUEUE_ROWS = [
  {
    id: 'APP-2024-00418',
    initials: 'RK',
    name: 'Rajesh Kumar',
    department: 'Revenue',
    service: 'Property Tax',
    priority: 'High',
    priorityTone: 'high',
    status: 'Assigned',
    statusTone: 'assigned',
    time: '6h 00m',
    stage: 1,
    verificationProgress: 0,
    appliedDate: '02 Jul 2024',
    assignedAt: '09:00 AM',
    applicant: {
      fullName: 'Rajesh Kumar',
      mobile: '+91 98765 43210',
      email: 'rajesh.kumar@email.com',
      address: '14/2, Gandhi Nagar, Bengaluru - 560001',
    },
    property: {
      surveyNo: 'SY-1247/3B',
      plotNo: 'Plot 42, Sector 7',
      totalArea: '240 sq.m',
      builtUpArea: '180 sq.m',
      propertyType: 'Residential',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Pending',
      amount: '₹12,400',
      dueDate: '10 Jul 2024',
      mode: 'Online',
    },
    verified: ['identity', 'property'],
    documents: [
      { id: 'aadhaar', title: 'Aadhaar Card', category: 'Identity', size: '1.2 MB', date: '02 Jul 2024', status: 'approved' },
      { id: 'pan', title: 'PAN Card', category: 'Identity', size: '0.8 MB', date: '02 Jul 2024', status: 'approved' },
      { id: 'plan', title: 'Property Plan', category: 'Property', size: '3.4 MB', date: '02 Jul 2024', status: 'pending' },
      { id: 'receipt', title: 'Property Tax Receipt', category: 'Property', size: '0.5 MB', date: '02 Jul 2024', status: 'pending' },
      { id: 'sitemap', title: 'Site Map', category: 'Property', size: '2.1 MB', date: '01 Jul 2024', status: 'rejected' },
      { id: 'encumbrance', title: 'Encumbrance Certificate', category: 'Legal', size: '1.7 MB', date: '01 Jul 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '28 Jun 2024 at 10:32 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '29 Jun 2024 at 09:00 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'started', title: 'Verification Started', time: '01 Jul 2024 at 10:15 AM', actor: 'Ravi Kumar (A1)', detail: 'Document review initiated', status: 'completed' },
      { id: 'query', title: 'Query Raised', time: '01 Jul 2024 at 03:20 PM', actor: 'Ravi Kumar (A1)', detail: 'Site map is unclear — customer to re-upload', status: 'completed' },
      { id: 'reupload', title: 'Customer Re-uploaded', time: '02 Jul 2024 at 11:05 AM', actor: 'Rajesh Kumar', detail: 'Updated site map uploaded', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [
      {
        id: 'note-1',
        author: 'Ravi Kumar',
        initials: 'RK',
        time: '01 Jul 2024 · 03:15 PM',
        text: 'Site map submitted by customer is unclear — plot boundaries not visible. Raised query for re-upload. Customer notified via SMS and email.',
      },
    ],
  },
  {
    id: 'APP-2024-00423',
    initials: 'DM',
    name: 'Deepak Mishra',
    department: 'Revenue',
    service: 'Property Tax',
    priority: 'Medium',
    priorityTone: 'medium',
    status: 'Assigned',
    statusTone: 'assigned',
    time: '1d 6h',
    stage: 1,
    verificationProgress: 0,
    appliedDate: '30 Jun 2024',
    assignedAt: '11:30 AM',
    applicant: {
      fullName: 'Deepak Mishra',
      mobile: '+91 98112 33894',
      email: 'deepak.mishra@email.com',
      address: 'Flat 9A, Harmony Heights, Bengaluru - 560037',
    },
    property: {
      surveyNo: 'SY-0982/1A',
      plotNo: 'Plot 9, Sector 3',
      totalArea: '145 sq.m',
      builtUpArea: '120 sq.m',
      propertyType: 'Apartment',
      zone: 'Zone B – Urban',
    },
    payment: {
      status: 'Received',
      amount: '₹8,250',
      dueDate: '08 Jul 2024',
      mode: 'UPI',
    },
    verified: ['identity'],
    documents: [
      { id: 'receipt', title: 'Tax Receipt', category: 'Payment', size: '0.4 MB', date: '30 Jun 2024', status: 'approved' },
      { id: 'ownership', title: 'Ownership Proof', category: 'Property', size: '1.0 MB', date: '30 Jun 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '30 Jun 2024 at 10:40 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '30 Jun 2024 at 11:30 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00420',
    initials: 'AV',
    name: 'Anand Verma',
    department: 'Revenue',
    service: 'Encumbrance Cert',
    priority: 'Medium',
    priorityTone: 'medium',
    status: 'Pending Verification',
    statusTone: 'pending',
    time: '6h 00m',
    stage: 2,
    verificationProgress: 0,
    appliedDate: '03 Jul 2024',
    assignedAt: '10:15 AM',
    applicant: {
      fullName: 'Anand Verma',
      mobile: '+91 99887 22145',
      email: 'anand.verma@email.com',
      address: 'B-204, Lotus Homes, Bengaluru - 560068',
    },
    property: {
      surveyNo: 'SY-3311/2C',
      plotNo: 'Plot 18, Sector 11',
      totalArea: '310 sq.m',
      builtUpArea: '210 sq.m',
      propertyType: 'Villa',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Pending',
      amount: '₹3,100',
      dueDate: '11 Jul 2024',
      mode: 'Online',
    },
    verified: ['identity', 'supporting'],
    documents: [
      { id: 'deed', title: 'Sale Deed', category: 'Legal', size: '2.1 MB', date: '03 Jul 2024', status: 'pending' },
      { id: 'mutation', title: 'Mutation Order', category: 'Legal', size: '0.6 MB', date: '03 Jul 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '03 Jul 2024 at 09:05 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '03 Jul 2024 at 09:40 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'started', title: 'Verification Started', time: '03 Jul 2024 at 10:15 AM', actor: 'Ravi Kumar (A1)', detail: 'Document review initiated', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [
      {
        id: 'note-1',
        author: 'Ravi Kumar',
        initials: 'RK',
        time: '03 Jul 2024 · 12:00 PM',
        text: 'Awaiting clarification on the encumbrance period before the certificate can be issued.',
      },
    ],
  },
  {
    id: 'APP-2024-00426',
    initials: 'AJ',
    name: 'Arun Joshi',
    department: 'Urban Dev',
    service: 'Zone Certificate',
    priority: 'High',
    priorityTone: 'high',
    status: 'Verification Started',
    statusTone: 'started',
    time: '2h 30m',
    stage: 2,
    verificationProgress: 60,
    appliedDate: '04 Jul 2024',
    assignedAt: '08:45 AM',
    applicant: {
      fullName: 'Arun Joshi',
      mobile: '+91 97531 66774',
      email: 'arun.joshi@email.com',
      address: 'Plot 42, Sector 7, Bengaluru - 560102',
    },
    property: {
      surveyNo: 'SY-7742/5D',
      plotNo: 'Plot 42, Sector 7',
      totalArea: '480 sq.m',
      builtUpArea: '360 sq.m',
      propertyType: 'Commercial',
      zone: 'Zone C – Mixed',
    },
    payment: {
      status: 'Received',
      amount: '₹9,600',
      dueDate: '06 Jul 2024',
      mode: 'Net Banking',
    },
    verified: ['identity', 'property', 'payment'],
    documents: [
      { id: 'layout', title: 'Site Layout', category: 'Planning', size: '2.8 MB', date: '04 Jul 2024', status: 'approved' },
      { id: 'noc', title: 'No Objection', category: 'Planning', size: '0.9 MB', date: '04 Jul 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '04 Jul 2024 at 08:00 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '04 Jul 2024 at 08:20 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'started', title: 'Verification Started', time: '04 Jul 2024 at 08:45 AM', actor: 'Ravi Kumar (A1)', detail: 'Site review scheduled', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00427',
    initials: 'NG',
    name: 'Nisha Gupta',
    department: 'Registration',
    service: 'Sale Deed',
    priority: 'Low',
    priorityTone: 'low',
    status: 'Pending Verification',
    statusTone: 'pending',
    time: '1d 4h',
    stage: 2,
    verificationProgress: 0,
    appliedDate: '01 Jul 2024',
    assignedAt: '02:10 PM',
    applicant: {
      fullName: 'Nisha Gupta',
      mobile: '+91 98322 11890',
      email: 'nisha.gupta@email.com',
      address: 'North Avenue, Pearl Lane, Bengaluru - 560045',
    },
    property: {
      surveyNo: 'SY-5108/4B',
      plotNo: 'Plot 7, Pearl Lane',
      totalArea: '200 sq.m',
      builtUpArea: '—',
      propertyType: 'Plot',
      zone: 'Zone B – Urban',
    },
    payment: {
      status: 'Pending',
      amount: '₹5,750',
      dueDate: '12 Jul 2024',
      mode: 'Online',
    },
    verified: ['identity'],
    documents: [
      { id: 'identity', title: 'Identity Proof', category: 'Legal', size: '0.7 MB', date: '01 Jul 2024', status: 'approved' },
      { id: 'agreement', title: 'Agreement Copy', category: 'Legal', size: '1.3 MB', date: '01 Jul 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '01 Jul 2024 at 01:20 PM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '01 Jul 2024 at 01:45 PM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'started', title: 'Verification Started', time: '01 Jul 2024 at 02:10 PM', actor: 'Ravi Kumar (A1)', detail: 'Waiting for legal clearance', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00419',
    initials: 'PS',
    name: 'Priya Sharma',
    department: 'Urban Dev',
    service: 'Building Plan',
    priority: 'High',
    priorityTone: 'high',
    status: 'Waiting Customer',
    statusTone: 'waiting',
    time: '4h 30m',
    stage: 2,
    verificationProgress: 0,
    appliedDate: '04 Jul 2024',
    assignedAt: '10:00 AM',
    applicant: {
      fullName: 'Priya Sharma',
      mobile: '+91 98811 34560',
      email: 'priya.sharma@email.com',
      address: 'Apt 21, River View, Bengaluru - 560016',
    },
    property: {
      surveyNo: 'SY-2290/8A',
      plotNo: 'Plot 21, River View',
      totalArea: '265 sq.m',
      builtUpArea: '190 sq.m',
      propertyType: 'Residential',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Received',
      amount: '₹16,900',
      dueDate: '07 Jul 2024',
      mode: 'UPI',
    },
    verified: ['identity', 'payment'],
    documents: [
      { id: 'elevation', title: 'Building Elevation', category: 'Planning', size: '3.1 MB', date: '04 Jul 2024', status: 'rejected' },
      { id: 'floor', title: 'Floor Plan', category: 'Planning', size: '1.8 MB', date: '04 Jul 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '04 Jul 2024 at 09:10 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '04 Jul 2024 at 09:30 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'query', title: 'Query Raised', time: '04 Jul 2024 at 10:00 AM', actor: 'Ravi Kumar (A1)', detail: 'Resubmission requested from the citizen', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [
      {
        id: 'note-1',
        author: 'Ravi Kumar',
        initials: 'RK',
        time: '04 Jul 2024 · 11:15 AM',
        text: 'Elevation drawing does not match the approved setback. Asked the customer to resubmit with corrected dimensions.',
      },
    ],
  },

  /* The applications the waiting-for-customer and forwarded screens list. They
     live here too so View on those rows opens a real detail page rather than
     the not-found branch. */
  {
    id: 'APP-2024-00421',
    initials: 'SP',
    name: 'Sunita Patel',
    department: 'Registration',
    service: 'Mutation',
    priority: 'Low',
    priorityTone: 'low',
    status: 'Query Raised',
    statusTone: 'query',
    time: '2h 15m',
    stage: 2,
    verificationProgress: 20,
    appliedDate: '29 Jun 2024',
    assignedAt: '11:20 AM',
    applicant: {
      fullName: 'Sunita Patel',
      mobile: '+91 90045 22187',
      email: 'sunita.patel@email.com',
      address: '7, Lake Road, Pune - 411004',
    },
    property: {
      surveyNo: 'SY-880/2C',
      plotNo: 'Plot 7, Lake Road',
      totalArea: '180 sq.m',
      builtUpArea: '120 sq.m',
      propertyType: 'Residential',
      zone: 'Zone B – Urban',
    },
    payment: {
      status: 'Pending',
      amount: '₹8,400',
      dueDate: '05 Jul 2024',
      mode: 'Net Banking',
    },
    verified: ['identity'],
    documents: [
      { id: 'sale-deed', title: 'Sale Deed', category: 'Legal', size: '2.4 MB', date: '29 Jun 2024', status: 'approved' },
      { id: 'mutation-form', title: 'Mutation Form', category: 'Registration', size: '0.9 MB', date: '29 Jun 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '29 Jun 2024 at 10:40 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '29 Jun 2024 at 11:20 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'query', title: 'Query Raised', time: '30 Jun 2024 at 09:05 AM', actor: 'Ravi Kumar (A1)', detail: 'Second clarification requested from the citizen', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00428',
    initials: 'VS',
    name: 'Vikram Singh',
    department: 'Revenue',
    service: 'Land Records',
    priority: 'High',
    priorityTone: 'high',
    status: 'Waiting Customer',
    statusTone: 'waiting',
    time: '1h 05m',
    stage: 2,
    verificationProgress: 35,
    appliedDate: '26 Jun 2024',
    assignedAt: '09:45 AM',
    applicant: {
      fullName: 'Vikram Singh',
      mobile: '+91 98220 71145',
      email: 'vikram.singh@email.com',
      address: '44, Civil Lines, Jaipur - 302006',
    },
    property: {
      surveyNo: 'SY-1502/9',
      plotNo: 'Plot 44, Civil Lines',
      totalArea: '420 sq.m',
      builtUpArea: '260 sq.m',
      propertyType: 'Residential',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Received',
      amount: '₹22,150',
      dueDate: '02 Jul 2024',
      mode: 'UPI',
    },
    verified: ['identity', 'property'],
    documents: [
      { id: 'khasra', title: 'Khasra Extract', category: 'Revenue', size: '1.5 MB', date: '26 Jun 2024', status: 'approved' },
      { id: 'boundary', title: 'Boundary Map', category: 'Revenue', size: '2.8 MB', date: '26 Jun 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '26 Jun 2024 at 09:00 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '26 Jun 2024 at 09:45 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'query', title: 'Query Raised', time: '27 Jun 2024 at 02:30 PM', actor: 'Ravi Kumar (A1)', detail: 'Boundary map is illegible; resubmission requested', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00422',
    initials: 'KR',
    name: 'Kiran Rao',
    department: 'Urban Dev',
    service: 'Land Use Change',
    priority: 'High',
    priorityTone: 'high',
    // The customer has already re-uploaded, so this one is back under review.
    status: 'Re-upload Received',
    statusTone: 'started',
    time: '3h 40m',
    stage: 2,
    verificationProgress: 50,
    appliedDate: '28 Jun 2024',
    assignedAt: '10:30 AM',
    applicant: {
      fullName: 'Kiran Rao',
      mobile: '+91 97400 65523',
      email: 'kiran.rao@email.com',
      address: '12, Nandi Layout, Bengaluru - 560032',
    },
    property: {
      surveyNo: 'SY-3310/1B',
      plotNo: 'Plot 12, Nandi Layout',
      totalArea: '310 sq.m',
      builtUpArea: '0 sq.m',
      propertyType: 'Vacant',
      zone: 'Zone C – Mixed Use',
    },
    payment: {
      status: 'Received',
      amount: '₹31,000',
      dueDate: '03 Jul 2024',
      mode: 'NEFT',
    },
    verified: ['identity', 'payment', 'supporting'],
    documents: [
      { id: 'site-map', title: 'Site Map (v2)', category: 'Planning', size: '2.1 MB', date: '02 Jul 2024', status: 'pending' },
      { id: 'zoning', title: 'Zoning Certificate', category: 'Planning', size: '1.1 MB', date: '28 Jun 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '28 Jun 2024 at 09:55 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'query', title: 'Query Raised', time: '29 Jun 2024 at 11:00 AM', actor: 'Ravi Kumar (A1)', detail: 'Superseded site map requested', status: 'completed' },
      { id: 'reupload', title: 'Documents Re-uploaded', time: '02 Jul 2024 at 04:20 PM', actor: 'Citizen Self', detail: 'Site_Map_v2.pdf replaces Site_Map_v1.pdf', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00425',
    initials: 'SI',
    name: 'Suresh Iyer',
    department: 'Urban Dev',
    service: 'Building Plan',
    priority: 'High',
    priorityTone: 'high',
    status: 'Forwarded',
    statusTone: 'forwarded',
    time: '—',
    stage: 4,
    verificationProgress: 100,
    appliedDate: '25 Jun 2024',
    assignedAt: '10:05 AM',
    applicant: {
      fullName: 'Suresh Iyer',
      mobile: '+91 98450 11298',
      email: 'suresh.iyer@email.com',
      address: '3, Temple Street, Chennai - 600028',
    },
    property: {
      surveyNo: 'SY-770/4A',
      plotNo: 'Plot 3, Temple Street',
      totalArea: '295 sq.m',
      builtUpArea: '210 sq.m',
      propertyType: 'Residential',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Received',
      amount: '₹19,750',
      dueDate: '30 Jun 2024',
      mode: 'UPI',
    },
    verified: ['identity', 'property', 'payment', 'signature', 'supporting', 'complete'],
    documents: [
      { id: 'plan', title: 'Building Plan', category: 'Planning', size: '4.2 MB', date: '25 Jun 2024', status: 'approved' },
      { id: 'noc', title: 'Fire NOC', category: 'Legal', size: '0.7 MB', date: '25 Jun 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '25 Jun 2024 at 09:20 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'verified', title: 'Verification Completed', time: '01 Jul 2024 at 05:00 PM', actor: 'Ravi Kumar (A1)', detail: 'All six checklist items cleared', status: 'completed' },
      { id: 'forwarded', title: 'Forwarded to Agent 2', time: '02 Jul 2024 at 10:15 AM', actor: 'Ravi Kumar (A1)', detail: 'Handed to Kavitha R. for final review', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00430',
    initials: 'MD',
    name: 'Mohan Das',
    department: 'Revenue',
    service: 'Property Tax',
    priority: 'Medium',
    priorityTone: 'medium',
    status: 'Approved',
    statusTone: 'approved',
    time: '—',
    stage: 3,
    verificationProgress: 100,
    appliedDate: '22 Jun 2024',
    assignedAt: '02:10 PM',
    applicant: {
      fullName: 'Mohan Das',
      mobile: '+91 99860 40072',
      email: 'mohan.das@email.com',
      address: '18, Market Road, Kochi - 682011',
    },
    property: {
      surveyNo: 'SY-2044/6',
      plotNo: 'Plot 18, Market Road',
      totalArea: '150 sq.m',
      builtUpArea: '150 sq.m',
      propertyType: 'Commercial',
      zone: 'Zone D – Commercial',
    },
    payment: {
      status: 'Received',
      amount: '₹12,300',
      dueDate: '28 Jun 2024',
      mode: 'Card',
    },
    verified: ['identity', 'property', 'payment', 'signature', 'supporting', 'complete'],
    documents: [
      { id: 'tax-receipt', title: 'Property Tax Receipt', category: 'Revenue', size: '0.6 MB', date: '22 Jun 2024', status: 'approved' },
      { id: 'ownership', title: 'Ownership Proof', category: 'Legal', size: '1.9 MB', date: '22 Jun 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '22 Jun 2024 at 01:30 PM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'verified', title: 'Verification Completed', time: '30 Jun 2024 at 04:45 PM', actor: 'Ravi Kumar (A1)', detail: 'All six checklist items cleared', status: 'completed' },
      { id: 'forwarded', title: 'Forwarded to Agent 2', time: '01 Jul 2024 at 09:30 AM', actor: 'Ravi Kumar (A1)', detail: 'Handed to Kavitha R. for final review', status: 'completed' },
      { id: 'approval', title: 'Approved by Agent 2', time: '03 Jul 2024 at 11:00 AM', actor: 'Kavitha R. (A2)', detail: 'Final approval granted', status: 'active' },
    ],
    notes: [],
  },
  {
    id: 'APP-2024-00431',
    initials: 'LM',
    name: 'Lalitha Menon',
    department: 'Registration',
    service: 'Encumbrance',
    priority: 'Low',
    priorityTone: 'low',
    status: 'Forwarded',
    statusTone: 'forwarded',
    time: '—',
    stage: 4,
    verificationProgress: 100,
    appliedDate: '20 Jun 2024',
    assignedAt: '03:40 PM',
    applicant: {
      fullName: 'Lalitha Menon',
      mobile: '+91 94470 33810',
      email: 'lalitha.menon@email.com',
      address: '9, Beach Road, Kozhikode - 673032',
    },
    property: {
      surveyNo: 'SY-1188/3',
      plotNo: 'Plot 9, Beach Road',
      totalArea: '205 sq.m',
      builtUpArea: '140 sq.m',
      propertyType: 'Residential',
      zone: 'Zone B – Urban',
    },
    payment: {
      status: 'Received',
      amount: '₹6,800',
      dueDate: '26 Jun 2024',
      mode: 'UPI',
    },
    verified: ['identity', 'property', 'payment', 'signature', 'supporting', 'complete'],
    documents: [
      { id: 'ec', title: 'Encumbrance Certificate', category: 'Legal', size: '1.7 MB', date: '20 Jun 2024', status: 'approved' },
      { id: 'identity', title: 'Aadhaar Card', category: 'Identity', size: '1.2 MB', date: '20 Jun 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '20 Jun 2024 at 03:00 PM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'verified', title: 'Verification Completed', time: '29 Jun 2024 at 12:20 PM', actor: 'Ravi Kumar (A1)', detail: 'All six checklist items cleared', status: 'completed' },
      { id: 'forwarded', title: 'Forwarded to Agent 2', time: '30 Jun 2024 at 02:00 PM', actor: 'Ravi Kumar (A1)', detail: 'Handed to Arjun K. for final review', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [],
  },
];
